# Generated by Django 4.2.18 on 2025-09-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blog_blogcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='SubSubCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsub', to='blog_app.subsubcategory'),
        ),
    ]
