# Generated by Django 4.2.18 on 2025-09-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blog_subsubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomments',
            name='parent',
        ),
    ]
