# Generated by Django 4.2.18 on 2025-09-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_remove_blogcomments_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='SubCategory',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='SubSubCategory',
            new_name='subsubcategory',
        ),
    ]
