# Generated by Django 5.1.3 on 2025-01-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_authenticate'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='para1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nav',
            name='para2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nav',
            name='para3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
