# Generated by Django 5.1.3 on 2025-01-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_nav_para1_nav_para2_nav_para3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='heading', max_length=255)),
                ('image', models.ImageField(upload_to='static/image')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='static/image')),
                ('author', models.CharField(default='heading', max_length=255)),
                ('content', models.TextField()),
                ('iframe', models.URLField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
