# Generated by Django 5.1.3 on 2025-01-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='heading',
            field=models.CharField(default='author', max_length=255),
        ),
    ]
