# Generated by Django 5.1.3 on 2025-01-01 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cat_name', to='blog_app.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='SubCategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat_name', to='blog_app.subcategory'),
            preserve_default=False,
        ),
    ]
