# Generated by Django 5.1.3 on 2025-01-01 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_blog_category_blog_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='Category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='catname', to='blog_app.category'),
            preserve_default=False,
        ),
    ]
