# Generated by Django 5.1.3 on 2025-01-01 21:53

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_blog_content1'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='heading', unique=True),
            preserve_default=False,
        ),
    ]
