# Generated by Django 5.1.3 on 2025-01-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
