# Generated by Django 5.1.3 on 2025-01-02 11:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_remove_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='heading', unique=True),
        ),
    ]
