# Generated by Django 5.1.3 on 2025-01-02 17:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_blog_new_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, max_length=255, null=True, populate_from='heading', unique=True),
        ),
    ]
