# Generated by Django 4.2.18 on 2025-08-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0020_dash_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dash',
        ),
        migrations.DeleteModel(
            name='logo',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
